name: Publish to Guardrails Hub

on:
  workflow_dispatch:
  push:
    # Publish when new releases are tagged.
    tags:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy
        uses: guardrails-ai/guardrails/.github/actions/validator_pypi_publish@main
        with:
          guardrails_token: ${{ secrets.GR_GUARDRAILS_TOKEN }}
          validator_id: guardrails/toxic_language